In [77]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [78]:
X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [79]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

clf = LogisticRegression()

clf.fit(X_train_scaled, y_train)

LogisticRegression()

In [80]:
clf.score(X_test_scaled, y_test)

0.956140350877193

In [81]:
single_instance = X_test_scaled[2]

In [82]:
single_instance

array([-0.26720785,  0.35299931, -0.23253453, -0.32396565, -0.68603043,
        0.11638505,  0.25328096, -0.34790577, -0.91435063, -0.36112049,
       -0.31851802, -0.79005169, -0.2638893 , -0.27596803,  0.05411468,
        0.37061823,  0.44075472,  0.11945285, -0.61259134, -0.20568624,
       -0.28690734, -0.02271375, -0.16854373, -0.32240569,  0.13097545,
        0.70964804,  0.88648385,  0.0767824 , -0.5438216 , -0.08505883])

In [83]:
clf.predict([single_instance])

array([1])

In [84]:
y_test[2]

np.int64(1)

In [85]:
clf.predict_proba([single_instance])

array([[0.26629715, 0.73370285]])