In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_iris(return_X_y=True)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
X_test_scaled

array([[-1.02536242, -0.18038282, -1.22235429, -1.31204989],
       [-0.18588442, -0.66140367,  0.17568722,  0.11456119],
       [-1.14528785,  0.06012761, -1.27827595, -1.31204989],
       [ 2.21262418, -0.18038282,  1.29412042,  1.41148036],
       [-0.30580985, -0.18038282,  0.17568722,  0.11456119],
       [ 0.41374273, -0.42089324,  0.28753054,  0.11456119],
       [ 0.17389187, -2.10446621,  0.67898216,  0.37394503],
       [-1.14528785,  0.06012761, -1.27827595, -1.44174181],
       [-0.06595899, -0.90191409,  0.17568722, -0.27451456],
       [ 1.01336988, -0.18038282,  0.79082548,  1.41148036],
       [-0.90543699,  1.74370057, -1.27827595, -1.18235798],
       [ 2.21262418, -1.14242451,  1.7414937 ,  1.41148036],
       [-0.18588442, -1.14242451, -0.15984275, -0.27451456],
       [ 0.89344445, -0.18038282,  0.3434522 ,  0.24425311],
       [-0.78551156,  2.46523184, -1.27827595, -1.44174181],
       [-1.62498957, -1.86395578, -1.39011927, -1.18235798],
       [ 0.77351902, -0.

In [12]:
import numpy as np
X_train_scaled_np = (X_train - np.mean(X_train, axis=0)) / np.std(X_train,axis=0)
X_train_scaled_np

#This is the same calculation as done before by using the StandardScaler

array([[-1.02536242,  0.78165888, -1.27827595, -1.31204989],
       [ 2.21262418, -0.66140367,  1.62965038,  1.02240461],
       [ 0.65359359,  0.06012761,  0.95859046,  0.76302078],
       [-1.02536242,  1.26267972, -1.33419761, -1.31204989],
       [ 2.09269875, -0.18038282,  1.57372872,  1.15209653],
       [-0.30580985, -0.18038282,  0.39937386,  0.37394503],
       [ 2.45247503,  1.74370057,  1.4618854 ,  1.02240461],
       [-0.42573527, -1.86395578,  0.11976556,  0.11456119],
       [-0.90543699,  1.0221693 , -1.33419761, -1.18235798],
       [ 1.85284789, -0.66140367,  1.29412042,  0.8927127 ],
       [ 1.13329531, -0.18038282,  0.95859046,  1.15209653],
       [ 0.65359359, -0.90191409,  0.84674714,  0.8927127 ],
       [-1.14528785,  1.26267972, -1.33419761, -1.44174181],
       [-0.06595899, -1.14242451,  0.11976556, -0.01513072],
       [ 0.41374273, -0.66140367,  0.56713884,  0.76302078],
       [ 1.25322074,  0.06012761,  0.9026688 ,  1.15209653],
       [ 0.2938173 , -0.

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
X_train_scaled

array([[0.19444444, 0.63636364, 0.0877193 , 0.04166667],
       [0.94444444, 0.36363636, 1.        , 0.79166667],
       [0.58333333, 0.5       , 0.78947368, 0.70833333],
       [0.19444444, 0.72727273, 0.07017544, 0.04166667],
       [0.91666667, 0.45454545, 0.98245614, 0.83333333],
       [0.36111111, 0.45454545, 0.61403509, 0.58333333],
       [1.        , 0.81818182, 0.94736842, 0.79166667],
       [0.33333333, 0.13636364, 0.52631579, 0.5       ],
       [0.22222222, 0.68181818, 0.07017544, 0.08333333],
       [0.86111111, 0.36363636, 0.89473684, 0.75      ],
       [0.69444444, 0.45454545, 0.78947368, 0.83333333],
       [0.58333333, 0.31818182, 0.75438596, 0.75      ],
       [0.16666667, 0.72727273, 0.07017544, 0.        ],
       [0.41666667, 0.27272727, 0.52631579, 0.45833333],
       [0.52777778, 0.36363636, 0.66666667, 0.70833333],
       [0.72222222, 0.5       , 0.77192982, 0.83333333],
       [0.5       , 0.36363636, 0.64912281, 0.45833333],
       [0.41666667, 0.90909091,

In [17]:
X_test_scaled

array([[0.19444444, 0.45454545, 0.10526316, 0.04166667],
       [0.38888889, 0.36363636, 0.54385965, 0.5       ],
       [0.16666667, 0.5       , 0.0877193 , 0.04166667],
       [0.94444444, 0.45454545, 0.89473684, 0.91666667],
       [0.36111111, 0.45454545, 0.54385965, 0.5       ],
       [0.52777778, 0.40909091, 0.57894737, 0.5       ],
       [0.47222222, 0.09090909, 0.70175439, 0.58333333],
       [0.16666667, 0.5       , 0.0877193 , 0.        ],
       [0.41666667, 0.31818182, 0.54385965, 0.375     ],
       [0.66666667, 0.45454545, 0.73684211, 0.91666667],
       [0.22222222, 0.81818182, 0.0877193 , 0.08333333],
       [0.94444444, 0.27272727, 1.03508772, 0.91666667],
       [0.38888889, 0.27272727, 0.43859649, 0.375     ],
       [0.63888889, 0.45454545, 0.59649123, 0.54166667],
       [0.25      , 0.95454545, 0.0877193 , 0.        ],
       [0.05555556, 0.13636364, 0.05263158, 0.08333333],
       [0.61111111, 0.45454545, 0.73684211, 0.79166667],
       [0.5       , 0.45454545,